### ISSUE TITLE
Testing float equality

### ISSUE THREAD

**Issue by jjones-99** [rucha2398/cs4500-a1-p2#12]
When testing equality with floats, `==` doesn't really work. For instance, `test1f()` uses lines like:

```
t_true(arr->float_get(0) == 1.2);
```

This fails for us because 1.2000... isn't exactly equal to 1.2.

We recommend doing something like:

```
void t_close(float f1, float f2) {
    if ((f1 - f2) > 0.01 || (f1 - f2) < -0.01) FAIL();
}
...
void test1f() {
    ...
    t_close(arr->float_get(0), 1.2);
    ...
}
```

**Comment by rucha2398** [comment]
Should be fixed now. Thank you!
