### ISSUE TITLE
Remaining Implementation Detail Hints

### ISSUE THREAD

**Issue by jsxtam** [rucha2398/cs4500-a1-p2#13]
I know we already asked this of you in #7 but there are some that are still present in your spec.

1.  `hash()` method for `Array`, `Object`, and `String` classes
* Please don't reveal how the hash is computed as this is an implementation detail users shouldn't know about.
2. `equals()` method for `Object`
* Again you are revealing how two `Objects` are equal, a detail users don't need

We are making this recommendation again as may lose points for it.

**Comment by rucha2398** [comment]
Should be fixed now! Thank you.
