### ISSUE TITLE
Standard Object & String

### ISSUE THREAD

**Issue by chasebish** [rucha2398/cs4500-a1-p2#14]
Hey could you update your object.h and string.h files to be consistent with this spec please?

https://piazza.com/class/k51bluky59n2jr?cid=345
https://github.com/chasebish/cwc_object_string

Thanks!

**Comment by chasebish** [comment]
Fixed in #21

**Comment by rucha2398** [comment]
Our tests use our String API, and since the assignment doesn't specify the exact behavior required on string, we don't feel the need to change the code just to add a couple of methods to the string class.
