### ISSUE TITLE
Float equality is backwards

### ISSUE THREAD

**Issue by jjones-99** [rucha2398/cs4500-a1-p2#16]
Hey! Going off of #12, thanks for adding the float comparison! But `float_equal()` actually does the opposite, since the comparison operators are switched.

It should be 
```
return (f1 - f2) < 0.01 || (f1 - f2) > -0.01;
```
rather than 
```
return (f1 - f2) > 0.01 || (f1 - f2) < -0.01;
```
to check if the difference is within the interval (-0.01, 0.01).

(This might be because you were going off of the `t_close()` function I showed, but that was checking if the float's _weren't_ close and then failing if `true`.)

**Comment by rucha2398** [comment]
Fixed it, thank you!
