### ISSUE TITLE
Remove copy constructor from Array

### ISSUE THREAD

**Issue by chasebish** [rucha2398/cs4500-a1-p2#17]
There is no point in copying an Array of Objects since they hold no data to copy, so it would make sense to remove the copy constructor from Array

**Comment by chasebish** [comment]
Same issue with `add_all`, would appreciate if that could be removed too

**Comment by chasebish** [comment]
Fixed in #21

**Comment by rucha2398** [comment]
I don't see why there's any need to remove the copy constructor. You can use the copy constructor to make a copy of the array and replace certain indices for example without changing the additional array. For example, we can imagine a sorting algorithm that would want to copy the input and not modify it.

**Comment by chasebish** [comment]
I have no issue with keeping the copy constructor in the sub classes. However in the parent Array class which only supports Objects this is an issue because an Object has no values to copy.

**Comment by chasebish** [comment]
When creating a copy of an Object Array it would be necessary to create a new Object. However, since Objects have no value to compare with, the way you compare the two is by checking if the two Objects have the same memory address. It would be wrong to copy an Object because then they would be in the same place in memory, and freeing one of them would free both of them.
