### ISSUE TITLE
index_of out of range handling

### ISSUE THREAD

**Issue by chasebish** [rucha2398/cs4500-a1-p2#18]
Can you change the functionality so that `index_of()` returns -1 instead of length+1 when the element is not found? -1 will be equal to the max size for a `size_t`

**Comment by rucha2398** [comment]
It doesn't make sense to return a negative value when the return type for index_of() is an unsigned int. The size of the array is easily checked, so it is easy to notice an error.

**Comment by chasebish** [comment]
`size_t = -1` will be equal to `SIZE_MAX` or `18446744073709551615`

It's just a little more readable in my opinion to do it this way

**Comment by chasebish** [comment]
I guess my interpretation works so this is a non-issue at this point
