### ISSUE TITLE
Remove virtual keyword from Array methods

### ISSUE THREAD

**Issue by chasebish** [rucha2398/cs4500-a1-p2#19]
Making methods in `array.h` is causing warnings in my compiler since there is type mismatch when overloading the method in inheriting classes. 

Can you remove the virtual keyword from the following methods in the Array class:
- index_of
- push
- add
- get
- set
- remove

Thanks!

**Comment by chasebish** [comment]
Fixed in #21

**Comment by rucha2398** [comment]
We would like to know the exact warnings you are getting, since we are not getting any on our part when we compile.

**Comment by chasebish** [comment]
<img width="927" alt="Screen Shot 2020-01-31 at 12 34 37 PM" src="https://user-images.githubusercontent.com/23260093/73560968-0d408680-4426-11ea-853c-c111e9afad6e.png">

**Comment by chasebish** [comment]
it's because the signature of the virtual function is different than the implemented one
