### ISSUE TITLE
Constructor Duplication

### ISSUE THREAD

**Issue by jjones-99** [rucha2398/cs4500-a1-p2#6]
`Array(size_t array_size)` and `Array(const size_t array_size)` don't compile together, as they're redeclarations of the same constructor. We request you choose one of the signatures to support in the API. For instance, the `const` doesn't matter as much in a simple case like this when passing by value.

If you'd rather keep both, you could change the second to `Array(const size_t &array_size)` to pass by a constant reference.

**Comment by rucha2398** [comment]
Have updated the code to reflect this issue.
