### ISSUE TITLE
Implementation Detail Hints

### ISSUE THREAD

**Issue by jjones-99** [rucha2398/cs4500-a1-p2#7]
Just bringing it to your attention, we've found a few hints to specific implementation details that you might want to remove, as you might lose points on the spec:

- In `README.md`, 
  - the `Object` section describes hashing as returning pointer values.
  - the `Array` section describes specific members of the class, especially how it is implemented with a capacity, etc.
- In `object.h`,
  - the comments for `equals(...)` and `hash()` describe using pointers.
- In `array.h`,
  - reveals the `grow_()` method and describes how it is used.

The API spec would be revealed to the public and doesn't need to reveal these details of the implementation—anything that is 'private' wouldn't need to (and probably shouldn't) be included.

_In [Piazza @317](https://piazza.com/class/k51bluky59n2jr?cid=317), it's said that "Q: What if there is already an implementation in the spec? A: Let the spec team know that if they don't remove it, they will lose points. Further, they need to purge it from the history. `git rm` is not nearly enough. Also, please write up this incident as a part of your report." Although this isn't a direct implementation, it hints towards one._

It's up to you if you make these changes or not.

**Comment by rucha2398** [comment]
Thank you! README is now updated with the removal of implementation details.
