### ISSUE TITLE
Memory Ownership

### ISSUE THREAD

**Issue by jjones-99** [rucha2398/cs4500-a1-p2#9]
Memory ownership is unclear in the spec. Does the user maintain ownership of all `Object`s added to the `Array` (faster), or does the `Array` take ownership of everything by copying (safer)?

One reason we're asking is because this distinction should be made clear by using `delete` on references in a corresponding manner in `test-array.cpp`.

**Comment by rucha2398** [comment]
Updated comments to reflect memory ownership. The elements of this array are not owned.
